// Generated by gencpp from file qb_interface/cubeCurrent.msg
// DO NOT EDIT!


#ifndef QB_INTERFACE_MESSAGE_CUBECURRENT_H
#define QB_INTERFACE_MESSAGE_CUBECURRENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qb_interface
{
template <class ContainerAllocator>
struct cubeCurrent_
{
  typedef cubeCurrent_<ContainerAllocator> Type;

  cubeCurrent_()
    : current_m1()
    , current_m2()  {
    }
  cubeCurrent_(const ContainerAllocator& _alloc)
    : current_m1(_alloc)
    , current_m2(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _current_m1_type;
  _current_m1_type current_m1;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _current_m2_type;
  _current_m2_type current_m2;




  typedef boost::shared_ptr< ::qb_interface::cubeCurrent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qb_interface::cubeCurrent_<ContainerAllocator> const> ConstPtr;

}; // struct cubeCurrent_

typedef ::qb_interface::cubeCurrent_<std::allocator<void> > cubeCurrent;

typedef boost::shared_ptr< ::qb_interface::cubeCurrent > cubeCurrentPtr;
typedef boost::shared_ptr< ::qb_interface::cubeCurrent const> cubeCurrentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qb_interface::cubeCurrent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qb_interface::cubeCurrent_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qb_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'qb_interface': ['/home/sirslab/ros_ws_handshake/src/qb_interface/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qb_interface::cubeCurrent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qb_interface::cubeCurrent_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qb_interface::cubeCurrent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qb_interface::cubeCurrent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qb_interface::cubeCurrent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qb_interface::cubeCurrent_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qb_interface::cubeCurrent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2eef53e05b04751a24e5c83cddf11cef";
  }

  static const char* value(const ::qb_interface::cubeCurrent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2eef53e05b04751aULL;
  static const uint64_t static_value2 = 0x24e5c83cddf11cefULL;
};

template<class ContainerAllocator>
struct DataType< ::qb_interface::cubeCurrent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qb_interface/cubeCurrent";
  }

  static const char* value(const ::qb_interface::cubeCurrent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qb_interface::cubeCurrent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] current_m1\n\
int32[] current_m2\n\
";
  }

  static const char* value(const ::qb_interface::cubeCurrent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qb_interface::cubeCurrent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_m1);
      stream.next(m.current_m2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cubeCurrent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qb_interface::cubeCurrent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qb_interface::cubeCurrent_<ContainerAllocator>& v)
  {
    s << indent << "current_m1[]" << std::endl;
    for (size_t i = 0; i < v.current_m1.size(); ++i)
    {
      s << indent << "  current_m1[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.current_m1[i]);
    }
    s << indent << "current_m2[]" << std::endl;
    for (size_t i = 0; i < v.current_m2.size(); ++i)
    {
      s << indent << "  current_m2[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.current_m2[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // QB_INTERFACE_MESSAGE_CUBECURRENT_H
