// Generated by gencpp from file qb_interface/handCurrent.msg
// DO NOT EDIT!


#ifndef QB_INTERFACE_MESSAGE_HANDCURRENT_H
#define QB_INTERFACE_MESSAGE_HANDCURRENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qb_interface
{
template <class ContainerAllocator>
struct handCurrent_
{
  typedef handCurrent_<ContainerAllocator> Type;

  handCurrent_()
    : current()  {
    }
  handCurrent_(const ContainerAllocator& _alloc)
    : current(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _current_type;
  _current_type current;




  typedef boost::shared_ptr< ::qb_interface::handCurrent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qb_interface::handCurrent_<ContainerAllocator> const> ConstPtr;

}; // struct handCurrent_

typedef ::qb_interface::handCurrent_<std::allocator<void> > handCurrent;

typedef boost::shared_ptr< ::qb_interface::handCurrent > handCurrentPtr;
typedef boost::shared_ptr< ::qb_interface::handCurrent const> handCurrentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qb_interface::handCurrent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qb_interface::handCurrent_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qb_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'qb_interface': ['/home/francesco/ros_ws_handshake/src/qb_interface/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qb_interface::handCurrent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qb_interface::handCurrent_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qb_interface::handCurrent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qb_interface::handCurrent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qb_interface::handCurrent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qb_interface::handCurrent_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qb_interface::handCurrent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d976b449f93ed52a0958824b07438fab";
  }

  static const char* value(const ::qb_interface::handCurrent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd976b449f93ed52aULL;
  static const uint64_t static_value2 = 0x0958824b07438fabULL;
};

template<class ContainerAllocator>
struct DataType< ::qb_interface::handCurrent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qb_interface/handCurrent";
  }

  static const char* value(const ::qb_interface::handCurrent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qb_interface::handCurrent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] current\n\
";
  }

  static const char* value(const ::qb_interface::handCurrent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qb_interface::handCurrent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct handCurrent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qb_interface::handCurrent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qb_interface::handCurrent_<ContainerAllocator>& v)
  {
    s << indent << "current[]" << std::endl;
    for (size_t i = 0; i < v.current.size(); ++i)
    {
      s << indent << "  current[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.current[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // QB_INTERFACE_MESSAGE_HANDCURRENT_H
