// Generated by gencpp from file qb_interface/handPos.msg
// DO NOT EDIT!


#ifndef QB_INTERFACE_MESSAGE_HANDPOS_H
#define QB_INTERFACE_MESSAGE_HANDPOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qb_interface
{
template <class ContainerAllocator>
struct handPos_
{
  typedef handPos_<ContainerAllocator> Type;

  handPos_()
    : closure()  {
    }
  handPos_(const ContainerAllocator& _alloc)
    : closure(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _closure_type;
  _closure_type closure;




  typedef boost::shared_ptr< ::qb_interface::handPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qb_interface::handPos_<ContainerAllocator> const> ConstPtr;

}; // struct handPos_

typedef ::qb_interface::handPos_<std::allocator<void> > handPos;

typedef boost::shared_ptr< ::qb_interface::handPos > handPosPtr;
typedef boost::shared_ptr< ::qb_interface::handPos const> handPosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qb_interface::handPos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qb_interface::handPos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qb_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'qb_interface': ['/home/sirslab/ros_ws_handshake/src/qb_interface/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qb_interface::handPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qb_interface::handPos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qb_interface::handPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qb_interface::handPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qb_interface::handPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qb_interface::handPos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qb_interface::handPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d3fcdda7faa52ddfc5831b96497f9ca";
  }

  static const char* value(const ::qb_interface::handPos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d3fcdda7faa52ddULL;
  static const uint64_t static_value2 = 0xfc5831b96497f9caULL;
};

template<class ContainerAllocator>
struct DataType< ::qb_interface::handPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qb_interface/handPos";
  }

  static const char* value(const ::qb_interface::handPos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qb_interface::handPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] closure\n\
";
  }

  static const char* value(const ::qb_interface::handPos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qb_interface::handPos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.closure);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct handPos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qb_interface::handPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qb_interface::handPos_<ContainerAllocator>& v)
  {
    s << indent << "closure[]" << std::endl;
    for (size_t i = 0; i < v.closure.size(); ++i)
    {
      s << indent << "  closure[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.closure[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // QB_INTERFACE_MESSAGE_HANDPOS_H
